### ISSUE TITLE
Add Unmapped VS Mapped States

### ISSUE THREAD

**Issue by coyiutoc** [coyiutoc/Honda-Capstone-Salmon#2]
Based on design spec, need to reduce opacity on an evidence that has been dragged into the workspace AND make it persist in the source list. 

- [x] Add mapped VS unmapped state onto evidence class
- [x] Add logic inside `updateColumnState` to prevent evidence from getting deleted from SOURCE list only 
- [x] Styling updates on an evidence that is unmapped VS mapped in the source list

**Comment by mattvalentine** [comment]
To show mapped cards as transparent, they need to be duplicated (one for each column it's mapped in, and one for the sidebar), and then if the mapped state is true, then it gets styled as such, and moved to the end of the list.

It looks like raw duplication causes lots of UI problems, so to handle things right there will need to be a bit more separation between model and view.

The backend should maintain a single list of evidence, and the front end will filter it, and create unique IDs for draggable cards to satisfy the front end library.

**Comment by mattvalentine** [comment]
I think I have behavior the way we want it.

Evidence now has 2 new attributes:
1. mapped is a count of the number of other columns a piece of evidence from the source list is included in

2. quoteid is a unique id that gets copied over to duplicate evidence in columns other than the source list for use in checking for the same quote already existing, and keeping the mapping counts accurate. It is an optional parameter in the constructor used only by the drag and drop. 

I'll need to tweak a few things in the dummy data, but nothing drastic.

I still need to do the styling of the mapped evidence.

**Do we want to sort the source list to have things mapped at the bottom?**

**Comment by coyiutoc** [comment]
@mattvalentine 

Hmm not sure about that. Would the sort auto-trigger when something previously unmapped gets dragged onto the board? Don't know if it's jarring to see it disappear/move down in the source list.... we can ask the others tomorrow.

Also we will have a checkbox filter for unmapped/mapped so don't know if that would be enough.

**Comment by mattvalentine** [comment]
@coyiutoc 

Yeah let's see what people think tomorrow. I've got mapping counts working well, and opacity drops when mapped is greater than 0.

**Comment by mattvalentine** [comment]
Drat! I think I just found a bug in the mapping count in a weird condition. It's a pretty easy condition to avoid during a demo, but we could trigger it by accident I guess.

**Comment by mattvalentine** [comment]
Bug fixed... new issue created for a tangentially related bug. Closing.
