### ISSUE TITLE
Cluster Reactivity

### ISSUE THREAD

**Issue by coyiutoc** [coyiutoc/Honda-Capstone-Salmon#4]
Currently hardcoded # of columns in the workspace. Might need to check expected behavior w/ design.

- [x] Dynamically add a new column if all the other columns are "clusters" (aka have more than 1 evidence)
- [x] Prob should not be a white blob to represent "empty" space - check w/ design ppl 
- [x] Fix CSS so will scroll horizontally on workspace area only as # of columns increases

**Comment by mattvalentine** [comment]
Adding is done, but deleting needs to be handled.

- [x] delete column when all elements are removed
